### ISSUE TITLE
warning about BLAS.vendor being deprecated on Julia v1.7

### ISSUE THREAD

**Issue by jishnub** [JuliaPy/PyCall.jl#922] opened 2021-09-17 06:16 UTC
I see the following warning on Julia 1.7 on using `PyPlot` (which seems to use `PyCall` internally):

```julia
┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
│   caller = npyinitialize() at numpy.jl:67
└ @ PyCall ~/.julia/packages/PyCall/tqyST/src/numpy.jl:67
PyObject <matplotlib.legend.Legend object at 0x7f8a5b854e50>
```

Sorry I don't have a repro immediately as the warning doesn't tell me where in my code this is happening. However this is clearly arising because `BLAS.vendor` is deprecated.

**Comment by stevengj** [comment] 2021-09-17 19:18
This is from here: https://github.com/JuliaPy/PyCall.jl/blob/5d227fc23fda631783a68c9ff1c6aff47200978e/src/numpy.jl#L67

Hopefully, this warning can just be removed in Julia 1.7, since I think #433 may finally be fixed by @staticfloat's new `libtrampoline` magic?

**Comment by staticfloat** [comment] 2021-09-17 19:32
Mmm, it's unclear to me what the root cause of #443 is; is it that Julia configures MKL to be 64-bit and Numpy expects it to be 32-bit?  If so, I guess someone needs to experiment with whether it's possible to load MKL as 32-bit and 64-bit at the same time with LBT.

**Comment by stevengj** [comment] 2021-09-18 11:31
> is it that Julia configures MKL to be 64-bit and Numpy expects it to be 32-bit

Yes.

**Comment by carstenbauer** [comment] 2021-12-06 11:40
Should we at least replace the `BLAS.vendor()` call with something like `any(contains("mkl"), getfield.(BLAS.get_config().loaded_libs, :libname))` to avoid the deprecation message before this is checked / worked out more carefully?

**Comment by devmotion** [comment] 2021-12-21 21:30
It would be good if the deprecation warning could be fixed (possibly as suggested by @carstenbauer) since the deprecation warnings break e.g. the doctests in PythonOT (https://github.com/JuliaOptimalTransport/PythonOT.jl/pull/18).

**Closed** 2022-03-03 06:52 UTC

**Comment by Ge0rges** [comment] 2022-07-17 02:17
I get a similar warning from a different file:

```
┌ Warning: `vendor()` is deprecated, use `BLAS.get_config()` and inspect the output instead
│   caller = (::DefaultLinSolve)(x::Vector{Float64}, A::Matrix{Float64}, b::Vector{Float64}, update_matrix::Bool; reltol::Float64, kwargs::Base.Pairs{Symbol, DiffEqBase.ScaleVector{Vector{Float64}}, Tuple{Symbol, Symbol}, NamedTuple{(:Pl, :Pr), Tuple{DiffEqBase.ScaleVector{Vector{Float64}}, DiffEqBase.ScaleVector{Vector{Float64}}}}}) at linear_nonlinear.jl:91
└ @ DiffEqBase ~/.julia/packages/DiffEqBase/niZxn/src/linear_nonlinear.jl:91
```
