### ISSUE TITLE
Build PyCall error

### ISSUE THREAD

**Issue by abieler** [JuliaPy/PyCall.jl#423] opened 2017-07-31 12:37 UTC
`Pkg.build("PyCall")` throws the error:
```
LoadError: UndefVarError: MINICONDA_VERSION not defined
while loading /home/abieler/.julia/v0.6/Conda/deps/build.jl, in expression start
ing on line 13
```

```julia
using PyCall
using Conda
```

do not throw any error however.

julia v0.6 on linux.
Conda: 0.6.0
PyCall: 1.14.0 (tried master too)

**Comment by stevengj** [comment] 2017-07-31 16:14
Duplicate of JuliaPy/Conda.jl#85 ... see there for [a workaround](https://github.com/JuliaPy/Conda.jl/issues/85#issuecomment-319118493).

**Closed by stevengj** 2017-07-31 16:14 UTC
