### ISSUE TITLE
configparser module doesn't work

### ISSUE THREAD

**Issue by hzxusx** [JuliaPy/PyCall.jl#477] opened 2018-03-28 08:23 UTC
The following code is directly adapted from [official Python documentation](https://docs.python.org/3/library/configparser.html). 
However, while it runs without any error or warning, the generated `test.ini` is empty.

```julia
using PyCall
@pyimport configparser

config = configparser.ConfigParser()
config["DEFAULT"] = Dict(
    "ServerAliveInterval"=>"45",
    "Compression"=>"yes",
    "CompressionLevel"=>9
)

@pywith pybuiltin("open")("test.ini", "w") as f begin
    config[:write](f)
end
```

Using PyDict doesn't help neither. 

I'm using Julia 0.6.1 and Python 3.6.4.

**Comment by stevengj** [comment] 2018-03-29 03:00
The problem is that your `config` is a `PyObject`, but `config["foo"]` for a PyCall `PyObject` is equivalent to `config.foo` in Python, not `config["foo"]`. 

This will be fixed once Julia 0.7 is out, since Julia 0.7 supports dot-overloading in Julia so that PyCall syntax will be able to mimic Python more closely.

For now, you can do:

```jl
julia> config = PyDict(pyimport("configparser")[:ConfigParser]())
PyCall.PyDict{PyCall.PyAny,PyCall.PyAny,false} with 1 entry:
  "DEFAULT" => PyObject <Section: DEFAULT>

julia> config["DEFAULT"] = Dict("ServerAliveInterval"=>"45", "Compression"=>"yes", "CompressionLevel"=>9);

julia> config.o[:write](STDOUT)
[DEFAULT]
compressionlevel = 9
serveraliveinterval = 45
compression = yes
```

**Closed by stevengj** 2018-03-29 03:00 UTC
