### ISSUE TITLE
Crash on pyimport of qiskit

### ISSUE THREAD

**Issue by nmoran** [JuliaPy/PyCall.jl#842] opened 2020-09-28 18:34 UTC
Crash on pyimport of qiskit. Using custom build of Julia 1.5.2, built with MKL and tried using both conda and pip versions of python. 

```
./julia -e "import PyCall; PyCall.pyimport(\"qiskit\")"
Segmentation fault (core dumped)
```

Full details including full backtrace at
https://gist.github.com/nmoran/ed25ad0819359cff1c19aef645f66f4a

**Comment by nmoran** [comment] 2020-09-30 10:20
Building with `USE_BLAS64 = 0` as is suggested in this issue https://github.com/JuliaPy/PyCall.jl/issues/443 seems to solve this.

**Comment by stevengj** [comment] 2020-10-01 12:40
Closing as a duplicate of #443.

**Closed by stevengj** 2020-10-01 12:40 UTC
