### ISSUE TITLE
Error when attempting to use the oct2py module

### ISSUE THREAD

**Issue by waldyrious** [JuliaPy/PyCall.jl#320] opened 2016-09-09 10:23 UTC
From [this julia-users thread](https://groups.google.com/d/topic/julia-users/nybwtyAe0Wk/discussion):

> from python I use [the] [oct2py](https://github.com/blink1073/oct2py) module to run octave functions with reasonably good results.
But in julia, using PyCall, this fails.
"@pyimport oct2py.octave as oc" leaves locked the command until you cancel it:

> 
    julia>pyimport oct2py.octave as oc
>
    ^ CERROR: function is not yet c-callable
    in pyinitialize at /home/rober/.julia/v0.4/PyCall/src/pyinit.jl:245
    in pyinitialize at /home/rober/.julia/v0.4/PyCall/src/pyinit.jl:305
    in pyimport at /home/rober/.julia/v0.4/PyCall/src/PyCall.jl:111

/cc @astromono

**Comment by stevengj** [comment] 2016-09-09 11:32
Are you using an out-of-date version of PyCall?  The error message makes no sense because [pyinit.jl](https://github.com/JuliaPy/PyCall.jl/blob/master/src/pyinit.jl) only has 115 lines (and is nowadays called when you import PyCall, not when you execute a pyimport).

Try `Pkg.update()`.  And look at `Pkg.status("PyCall")` to make sure that you haven't pinned PyCall at an old version.

**Comment by waldyrious** [comment] 2016-09-09 14:34
Just to be clear, I wasn't the original reporter, I merely copied the message from @astromono in the list and made it an issue here as you suggested in that thread, so that it would be tracked. The message dates from Feb 2015, so [this](https://github.com/JuliaPy/PyCall.jl/blob/0254dc3/src/pyinit.jl) would be (at most) what `pyinit.jl` would have looked like at the time. It's possible that with all the changes made since then the issue has been fixed, but if so, it will still be a net benefit to have this explicitly stated here :)

**Comment by stevengj** [comment] 2016-09-09 17:28
Okay.  I don't have oct2py, though, so I'm going to close this issue unless it can be reproduced with the current version.

**Closed by stevengj** 2016-09-09 17:28 UTC

**Comment by waldyrious** [comment] 2016-09-09 18:31
Fair enough.
