### ISSUE TITLE
PyCall.version yields v"0.0.0" with Matplotlib 2.1.0

### ISSUE THREAD

**Issue by wg030** [JuliaPy/PyCall.jl#448] opened 2017-11-15 13:20 UTC
Hey everybody,
I've just installed the latest versions of Julia and Atom with Juno on an Ubuntu 16.04 LTS PC.
When I wanted to create a plot with the Plots package using the pyplot backend I got the warning
> WARNING: You are using Matplotlib 0.0.0, which is no longer officialy supported by the Plots community. To ensure smooth Plots.jl integration update your Matplotlib library to a version >= 2.0.0

followed by the error

> LoadError: KeyError: key "set_axis_bgcolor" not found
while loading ..../model.jl, in expression starting on line 144
getindex(::PyCall.PyObject, ::String) at PyCall.jl:247
getindex(::PyPlot.Figure, ::Symbol) at PyPlot.jl:68
_before_layout_calcs(::Plots.Plot{Plots.PyPlotBackend}) at pyplot.jl:939
prepare_output(::Plots.Plot{Plots.PyPlotBackend}) at plot.jl:251
display at output.jl:144 [inlined]
gui at output.jl:134 [inlined]
macro expansion at model.jl:158 [inlined]
anonymous at <missing>:?
include_string(::String, ::String) at loading.jl:522
include_string(::Module, ::String, ::String) at Compat.jl:478
(::Atom.##57#60{String,String})() at eval.jl:74
withpath(::Atom.##57#60{String,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
macro expansion at eval.jl:72 [inlined]
(::Atom.##56#59{Dict{String,Any}})() at task.jl:80

My Matplotlib version is the latest (2.1.0), which I installed from source according to the instructions on the official homepage ([https://matplotlib.org/faq/installing_faq.html#install-from-git](https://matplotlib.org/faq/installing_faq.html#install-from-git)). When I type "pip show matplotlib" in the terminal it confirms that the installation was successful showing the exact version number "2.1.0+806.g905465b".

Having looked at the source code of "pyplot.jl" I have figured out that the problem is likely a problem of the PyCall package (or maybe even Matplotlib itself) and not the Plots package since the call `PyCall.version` does not yield the right version number of Matplotlib.

So I am posting it here, although my quick fix is a slight modification of Plots package "pyplot.jl" file. So what I did to get rid of that error is the following: I simply changed the line `const set_facecolor_sym = if PyPlot.version < v"2"` of my local "/home/myusername/.julia/v0.6/Plots/src/backends/pyplot.jl" file to `const set_facecolor_sym = if v"0" < PyPlot.version < v"2"`. Everything works as expected now.

**Comment by stevengj** [comment] 2017-11-15 13:31
Are you sure that PyCall is using the same version of `python` that you are using with `pip`?   What is `PyCall.python`?

`PyPlot.version` is computed via `convert(VersionNumber, matplotlib[:__version__])` and it gets `0.0` if this fails to parse.   So what does `PyPlot.matplotlib[:__version__]` give?

**Comment by wg030** [comment] 2017-11-15 13:43
> Are you sure that PyCall is using the same version of python that you are using with pip?

No, I am not. How can I check this out? During the installation of Matplotlib I also installed pip via apt-get with the commands "sudo apt-get install python-pip" and "sudo pip install --upgrade pip"


> What is `PyCall.python`?

This yields "/usr/bin/python".


> So what does `PyPlot.matplotlib[:__version__]` give?

This yields "2.1.0.post806+g905465b". Pretty strange considering your nice explanation.

**Comment by stevengj** [comment] 2017-11-15 14:05
Okay, the problem is that `"2.1.0.post806+g905465b"` does not parse as a `VersionNumber`

Right now, the `VersionNumber` parsing in Julia is tied to the semver spec, so it gets confused on non-semver numbers, see #7282.

To get it to parse without throwing away data, it looks like the version number would need to be massaged into something like `convert(VersionNumber, "2.1.0+post806-g905465b")`.

Probably PyPlot should just strip everything after the third decimal point.

**Comment by stevengj** [comment] 2017-11-15 14:16
Should be fixed by https://github.com/JuliaPy/PyPlot.jl/commit/2476177334dd0640711c2ca5d2c5c6bb0dc3c317

**Comment by stevengj** [comment] 2017-11-15 14:16
(Just noticed that this issue was accidentally filed for PyCall, not PyPlot: we are talking about `PyPlot.version` here, not `PyCall.version`.)

**Closed by stevengj** 2017-11-15 14:16 UTC
