### ISSUE TITLE
PyCall Building error ReadOnlyMemoryError

### ISSUE THREAD

**Issue by kendrick1501** [JuliaPy/PyCall.jl#380] opened 2017-04-12 10:17 UTC
Hi Guys!

Before the last update of "PyCall.jl" I was able to utilize the package "SerialPorts.jl" without any problem. But now, with the last update of "PyCall.jl" the following error is displayed everytime I tried to build PyCall again.

=======================[ ERROR: PyCall ]=============
LoadError: ReadOnlyMemoryError()
while loading C:\.julia\v0.5\PyCall\deps\build.jl, in expression starting on lin
e 258
=======================================

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x77b9eaab -- RtlAllocateHeap at C:\Win
dows\SYSTEM32\ntdll.dll (unknown line)
while loading no file, in expression starting on line 0
RtlAllocateHeap at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
HeapFree at C:\Windows\system32\kernel32.dll (unknown line)
free at C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.61
61_none_08e61857a83bc251\MSVCR90.dll (unknown line)
freefls at C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729
.6161_none_08e61857a83bc251\MSVCR90.dll (unknown line)
RtlProcessFlsData at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
LdrShutdownProcess at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
RtlExitUserProcess at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
wcstoui64 at C:\Windows\system32\msvcrt.dll (unknown line)
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-4.0.6-1/crt\crtexe.c:
335
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-4.0.6-1/crt\crtexe.c:212

BaseThreadInitThunk at C:\Windows\system32\kernel32.dll (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
Allocations: 2599097 (Pool: 2598094; Big: 1003); GC: 2

===============[ BUILD ERRORS]========================
WARNING: PyCall had build errors.

 - packages with build errors remain installed in C:\.julia\v0.5
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script
=================================================

**My system information is**

Julia Version 0.5.1
Commit 6445c82 (2017-03-05 13:25 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)

What can I do to get SerialPorts running again? I have already re-installed Julia and all packages with no success thus far.

**Comment by stevengj** [comment] 2017-04-12 13:10
What version of Python are you using?

Can you try a `git bisect` on PyCall to see where the problem was introduced?

**Comment by stevengj** [comment] 2017-04-19 18:49
Can you try it with the latest PyCall?  `Pkg.checkout("PyCall")` and `Pkg.build("PyCall")` again.

**Comment by kendrick1501** [comment] 2017-04-20 01:47
Steven sorry for my late response,

The problem was solved. I did the following:

1. Installed Python 2.7.3 and pointed Julia to it (ENV["PYTHON"]="C:/...")
2. I tried to rebuild SerialPorts and failed because PyCall was not able to rebuild.
3. Then, pointed back to Julia own python package (ENV["PYTHON"]=""), and tried again with SerialPorts. The error wasn't there anymore.

Do you have any idea what happened there?

Thanks!

**Comment by stevengj** [comment] 2017-04-20 12:36
As to why PyCall "was not able to rebuild" with your local Python, that depends on what Python distro you were using and whether it was working outside of Julia, and other information you haven't supplied.

If you can no longer reproduce the problem, however, it would be best to close this issue.

**Comment by kendrick1501** [comment] 2017-04-20 12:58
I think so too.

Thanks, Steven.

**Closed** 2017-04-20 15:57 UTC
