### ISSUE TITLE
Error when trying to use scipy.optimize

### ISSUE THREAD

**Issue by mxkramer** [JuliaPy/PyCall.jl#367] opened 2017-02-24 22:25 UTC
When I try to use `scipy.optimize.curve_fit`, I get an error:

```julia
@pyimport scipy.optimize as so
so.curve_fit((x, a, b) -> a*sin(x * b), xdata, ydata
```

Gives me the error:

```julia
PyError (:PyObject_Call) <class 'ValueError'>
ValueError('callable <PyCall.jlwrap #17> is not supported by signature',)
  File "/usr/local/lib/python3.6/site-packages/scipy/optimize/minpack.py", line 629, in curve_fit
    args, varargs, varkw, defaults = _getargspec(f)
  File "/usr/local/lib/python3.6/site-packages/scipy/_lib/_util.py", line 280, in getargspec_no_self
    sig = inspect.signature(func)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 3002, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 2752, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 2339, in _signature_from_callable
    raise ValueError('callable {!r} is not supported by signature'.format(obj))
```

It seems like Julia functions don't support Python's signature check (makes sense because of methods). Is there a way around that?

**Comment by stevengj** [comment] 2017-02-24 22:45
Seems like a duplicate of #268.   For now, the workaround is to wrap the Julia function in a `lambda` .

**Closed by stevengj** 2017-02-24 22:45 UTC
