### ISSUE TITLE
Installing PyCall on JuliaPro 1.4.1 Fails

### ISSUE THREAD

**Issue by RoyiAvital** [JuliaPy/PyCall.jl#767] opened 2020-04-23 16:19 UTC
When I ran `Pkg.add("PyCall")` I got the following:

```
Resolving package versions...
  Installed PyCall ─ v1.91.4
   Updating `D:\Applications\Programming\JuliaProMKL\Profile\.juliapro\JuliaPro_v1.4.1-1\environments\v1.4\Project.toml`
  [438e738f] + PyCall v1.91.4
   Updating `D:\Applications\Programming\JuliaProMKL\Profile\.juliapro\JuliaPro_v1.4.1-1\environments\v1.4\Manifest.toml`
  [438e738f] + PyCall v1.91.4
   Building PyCall → `D:\Applications\Programming\JuliaProMKL\Profile\.juliapro\JuliaPro_v1.4.1-1\packages\PyCall\zqDXB\deps\build.log`
┌ Error: Error building `PyCall`: 
│ ERROR: LoadError: ArgumentError: Path to conda environment is not valid: C:\Users\<UserName>\.juliapro\JuliaPro_v1.4.1-1\Conda_env
│ Stacktrace:
│  [1] prefix(::String) at D:\Applications\Programming\JuliaProMKL\Profile\.juliapro\JuliaPro_v1.4.1-1\packages\Conda\3rPhK\src\Conda.jl:41
│  [2] top-level scope at D:\Applications\Programming\JuliaProMKL\Profile\.juliapro\JuliaPro_v1.4.1-1\packages\Conda\3rPhK\src\Conda.jl:46
│  [3] include(::Module, ::String) at .\Base.jl:377
│  [4] top-level scope at none:2
│  [5] eval at .\boot.jl:331 [inlined]
│  [6] eval(::Expr) at .\client.jl:449
│  [7] top-level scope at .\none:3
│ in expression starting at D:\Applications\Programming\JuliaProMKL\Profile\.juliapro\JuliaPro_v1.4.1-1\packages\Conda\3rPhK\src\Conda.jl:46
│ ERROR: LoadError: Failed to precompile Conda [8f4d0f93-b110-5947-807f-2305c1781a2d] to D:\Applications\Programming\JuliaProMKL\Profile\.juliapro\JuliaPro_v1.4.1-1\compiled\v1.4\Conda\WZE3U_PNArJ.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
│  [3] _require(::Base.PkgId) at .\loading.jl:1029
│  [4] require(::Base.PkgId) at .\loading.jl:927
│  [5] require(::Module, ::Symbol) at .\loading.jl:922
│  [6] include(::String) at .\client.jl:439
│  [7] top-level scope at none:5
│ in expression starting at D:\Applications\Programming\JuliaProMKL\Profile\.juliapro\JuliaPro_v1.4.1-1\packages\PyCall\zqDXB\deps\build.jl:9
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.4.1\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:892
```
Where I replaced my actual *User Name* with `<UserName>`.

The issue Is I'm running Julia in [Portable Mode](https://discourse.julialang.org/t/29831). So Environment Variable are set manually.

Why is `PyCall` looking for `C:\Users\<UserName>\.juliapro\JuliaPro_v1.4.1-1\Conda_env` when:

```
julia> ENV["APPDATA"]
"D:\\Applications\\Programming\\JuliaProMKL\\Profile\\AppData"

julia> ENV["USERPROFILE"]
"D:\\Applications\\Programming\\JuliaProMKL\\Profile"

julia> ENV["HOMEPATH"]
"D:\\Applications\\Programming\\JuliaProMKL\\Profile"

julia> ENV["ProgramData"]
"D:\\Applications\\Programming\\JuliaProMKL\\Profile\\ProgramData"

julia> ENV["Public"]
"D:\\Applications\\Programming\\JuliaProMKL\\Profile\\Public"
```

Namely it seems `PyCall` doesn't use the Environment Variables to infer correct paths.

**Comment by RoyiAvital** [comment] 2020-04-23 18:06
OK, I found the the issue and how to fix it manually.
I am not sure what caused it though (Which should be fixed in the package probably).

The package `Conda.jl` creates a file called `deps.jl` on installation.
It has a constant called `ROOTENV` which for some reason was set to `"C:\\Users\\<UserName>\\.juliapro\\JuliaPro_v1.4.1-1\\Conda_env"`.

It is created by `https://github.com/JuliaPy/Conda.jl/blob/master/deps/build.jl` but I don't see what's there caused to set `ROOTENV` the way it did.

**Comment by stevengj** [comment] 2020-05-02 15:33
Closing as a duplicate of JuliaPy/Conda.jl/issues/179

**Closed by stevengj** 2020-05-02 15:33 UTC
