### ISSUE TITLE
big performance hit in converting arrays recently introduced

### ISSUE THREAD

**Issue by marius311** [JuliaPy/PyCall.jl#672] opened 2019-03-29 00:27 UTC
I noticed conversion from Python arrays seems to be much slower than I had remembered. I'm not sure exactly what did it, but here's an example:

On PyCall 1.18.5 I get

```julia
julia> py"""
       from numpy.random import rand
       x = rand(4096,4096)
       """;

julia> @btime py"x"
  315.411 ms (71 allocations: 128.00 MiB)
```

whereas on 1.90.0 (the next major release which added the getproperty stuff), its ~13 times slower:

```julia
julia> @btime py"x"
  3.998 s (67108917 allocations: 2.13 GiB)
```

**Comment by stevengj** [comment] 2019-03-29 01:20
Has it accidentally changed which conversion method it is calling?  It should be calling [this method](https://github.com/JuliaPy/PyCall.jl/blob/2a7bb25e19c08806fbf2c806d65dfcb8dafcd3e4/src/pyarray.jl#L267)

**Comment by tkf** [comment] 2019-03-29 04:21
> It should be calling [this method](https://github.com/JuliaPy/PyCall.jl/blob/2a7bb25e19c08806fbf2c806d65dfcb8dafcd3e4/src/pyarray.jl#L267)

`pyocopy` is still called but it looks like we are hitting the generic `copyto!(dest::AbstractArray{T,N}, src::AbstractArray{T,N})` here

https://github.com/JuliaPy/PyCall.jl/blob/2a7bb25e19c08806fbf2c806d65dfcb8dafcd3e4/src/pyarray.jl#L145-L155

OTOH `py"x.T"` is super fast.  Maybe use `NoCopyArray` and `permutedims!`?

A bit tangential but why we are not using `NoCopyArray` in the default conversion?

**Comment by stevengj** [comment] 2019-03-29 11:10
But it seems like it would have to be using the same method before?  Why is it slower?  (The only difference is that I added `GC.@preserve` and bounds checks to `getindex`.)

**Comment by stevengj** [comment] 2019-03-29 19:25
> why we are not using `NoCopyArray` in the default conversion?

Because that type is experimental and unreliable — in particular, it is totally unsafe with respect to garbage collection.  (It has no protection against the Python array being garbage-collected out from under the Julia `Array`.)

I'd rather just get `PyArray` functional enough that we can return that by default for numpy types.

**Comment by stevengj** [comment] 2019-03-29 19:40
Regarding the current issue, the problem is that `getindex(::PyArray, ::CartesianIndex)` is allocating, apparently due to a type instability, which is causing the massive slowdown.

**Comment by stevengj** [comment] 2019-03-29 19:48
Should be fixed on master

**Closed** 2019-03-29 19:48 UTC

**Comment by marius311** [comment] 2019-03-29 20:26
Awesome, thanks for the quick fix guys!
