### ISSUE TITLE
No module named site

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaPy/PyCall.jl#382] opened 2017-04-17 22:43 UTC
When I try:

```
Pkg.build("PyDSTool")
INFO: Building Conda
INFO: Building PyCall
Fetching package metadata ...
..
......
Solving package specifications: .
.
........

# All requested packages already installed.
# packages in environment at C:\Users\Chris\.julia\v0.5\Conda\deps\usr:
#
numpy                     1.12.1                   py27_0  
INFO: PyCall is using C:\Users\Chris\.julia\v0.5\Conda\deps\usr\python.exe (Python 2.7.13) at C:\Users\Chris\.julia\v0.5\Conda\deps\usr\python.exe, libpython = C:\Users\Chris\.julia\v0.5\Conda\deps\usr\python27
INFO: C:\Users\Chris\.julia\v0.5\PyCall\deps\deps.jl has not changed
INFO: C:\Users\Chris\.julia\v0.5\PyCall\deps\PYTHON has not changed
INFO: Building PyDSTool
ImportError: No module named site
```

it fails on Windows. But I can copy/paste the build script

```julia
    Conda.add("scipy")
    Conda.add_channel("conda-forge")
    Conda.add("pydstool")
```

It works. It seems this is a very common issue on Windows:

https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/149

The solution is

```julia
Pkg.pin("PyCall",v"1.11.0")
```

so I think one of those changes must've caused this.

**Comment by stevengj** [comment] 2017-04-18 03:00
Can you do a git bisect?

**Comment by ChrisRackauckas** [comment] 2017-04-18 03:14
It was this commit:

https://github.com/JuliaPy/PyCall.jl/commit/cc00c474933a6554235e37cccb6eb1560553822c

**Comment by stevengj** [comment] 2017-04-18 14:02
What is PYTHONHOME in PyCall/deps/deps.jl?   Does it work if you change this to the empty string?

**Comment by ChrisRackauckas** [comment] 2017-04-18 14:23
```
const python = "C:\\Users\\Chris\\.julia\\v0.5\\Conda\\deps\\usr\\python.exe"
const libpython = "C:\\Users\\Chris\\.julia\\v0.5\\Conda\\deps\\usr\\python27"
const pyprogramname = "C:\\Users\\Chris\\.julia\\v0.5\\Conda\\deps\\usr\\python.exe"
const wpyprogramname = Base.cconvert(Cwstring, "C:\\Users\\Chris\\.julia\\v0.5\\Conda\\deps\\usr\\python.exe")
const pyversion_build = v"2.7.13"
const PYTHONHOME = "C:\\Users\\Chris\\.julia\\v0.5\\Conda\\deps\\usr"
const wPYTHONHOME = Base.cconvert(Cwstring, "C:\\Users\\Chris\\.julia\\v0.5\\Conda\\deps\\usr")

"True if we are using the Python distribution in the Conda package."
const conda = true
```

Building PyDSTool for some reason causes PyCall to rebuild, and puts back in the Python home. So I can't use an empty string really.

**Comment by ChrisRackauckas** [comment] 2017-04-19 13:13
Is there any way to force PyCall to not rebuild?

**Comment by stevengj** [comment] 2017-04-19 17:55
I was able to reproduce your problem, and it seems to be fixed by d086561fbbd39c48f1c214f642103a9b87b39a0e if you do a `Pkg.checkout("PyCall")`.

**Comment by ChrisRackauckas** [comment] 2017-04-19 18:00
Great! Works on master.

When do you plan on doing your next release?

**Comment by stevengj** [comment] 2017-04-19 18:46
I'm planning on doing another release as soon as tests are green.

**Comment by ChrisRackauckas** [comment] 2017-04-19 18:47
Sounds good. Thanks!

**Closed by stevengj** 2017-04-19 18:46 UTC

**Comment by stevengj** [comment] 2017-04-19 19:21
JuliaLang/METADATA.jl#8924
